server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.14.148:3100/loki/api/v1/push

scrape_configs:
  - job_name: "conpot"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "conpot"
          __path__: /home/bbrain/conpot_logs/conpot.json
          
  - job_name: "fake_shell_logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "fake_shell"
          host: "conpot_server"
          __path__: "/home/bbrain/conpot_logs/fake_shell_commands.log"
